Fixed Issue #17, user was able to delete message of other users.
Creatoon/Jar-web-app pull request #55
Opened 2021-06-20 09:50 UTC by sanskarbansal

Fixes #17 

#### Short description of what this resolves:
Earlier user was able to delete other users message, this PR fixes this issue by checking in backend if the user who is deleting the post is the one who is logged in or not. 

#### Changes proposed in this pull request:
- In index.js (client) verify that the whether to show delete message button or not. 
- In backend verify if the user who is deleting the post is the one who is logged in . 

#### Checklist

- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

2021-06-20 09:51 UTC, sanskarbansal commented
@Creatoon please review my PR.

2021-06-21 10:31 UTC, Creatoon requested changes

2021-06-21 10:31 UTC, Creatoon commented on controllers/messageController.js
> +  //   factory.deleteOne(Chat);
```suggestion
 
```

2021-06-21 10:32 UTC, Creatoon commented
@sanskarbansal Good Job 👍🏽

2021-06-21 10:32 UTC, merged